const meghalayaQA = {
  // ===================== GENERAL INFO =====================
  "what is the capital of meghalaya": "Shillong is the capital of Meghalaya.",
  "where is meghalaya located": "Meghalaya is in Northeast India, bordered by Assam and Bangladesh.",
  "what is the meaning of meghalaya": "Meghalaya means 'Abode of Clouds' in Sanskrit.",
  "is meghalaya safe for solo travelers": "Yes, Meghalaya is one of the safest states in India for solo travelers.",
  "what language is spoken in meghalaya": "Khasi, Garo, Jaintia, and English are widely spoken.",
  "what is the population of meghalaya": "Meghalaya has a population of about 3.5 million.",
  "best time to visit meghalaya": "October to April is the best time to visit Meghalaya.",
  "how many districts are in meghalaya": "There are 12 districts in Meghalaya.",
  "currency used in meghalaya": "Indian Rupee (INR) is used in Meghalaya.",
  "famous nickname of meghalaya": "Meghalaya is called the 'Scotland of the East'.",

  // ===================== ATTRACTIONS =====================
  "famous places in shillong": "Ward’s Lake, Shillong Peak, Elephant Falls, Police Bazaar.",
  "tell me about cherrapunji": "Cherrapunji is famous for its heavy rainfall, living root bridges, and Nohkalikai Falls.",
  "how tall is nohkalikai falls": "Nohkalikai Falls is 340 meters tall, the tallest plunge waterfall in India.",
  "double decker root bridge trek time": "The trek takes around 3–4 hours round trip.",
  "what is dawki famous for": "Dawki is famous for its crystal-clear Umngot River where boats seem to float in the air.",
  "cleanest village in asia": "Mawlynnong in Meghalaya is known as the cleanest village in Asia.",
  "famous caves in meghalaya": "Mawsmai Cave, Siju Cave, and Liat Prah are popular caves.",
  "what is shillong peak": "Shillong Peak offers panoramic views of the city and surroundings.",
  "popular waterfall in meghalaya": "Krang Suri Falls is one of the most scenic waterfalls.",
  "living root bridge location": "They are found in Cherrapunji and Mawlynnong region.",

  // ===================== FOOD & PRICES =====================
  "famous food of meghalaya": "Jadoh, Doh Khleh, Tungrymbai, and Bamboo Shoots.",
  "price of jadoh": "Jadoh costs around ₹80–₹150 per plate.",
  "price of khasi pork curry": "Khasi pork curry is about ₹150–₹250 per plate.",
  "cost of bamboo shoot pickle": "Around ₹50–₹100 per jar in local markets.",
  "where to eat local food in shillong": "Police Bazaar and local Khasi eateries are great options.",
  "what is tungrymbai": "Tungrymbai is a fermented soybean dish cooked with pork.",
  "vegetarian food in meghalaya": "Yes, you can find vegetarian food like Jhur Sideh and Pumaloi.",
  "street food in shillong": "Momos, chowmein, and jadoh are common street foods.",
  "cost of momos in shillong": "Momos cost about ₹50–₹120 per plate.",
  "cost of tea in meghalaya": "A cup of tea costs ₹10–₹20.",

  // ===================== SHOPPING =====================
  "where to shop in shillong": "Police Bazaar and Bara Bazaar are popular shopping hubs.",
  "famous things to buy in meghalaya": "Handwoven shawls, bamboo crafts, organic honey, oranges.",
  "price of khasi shawls": "Khasi shawls cost ₹500–₹1200 depending on material.",
  "local handicrafts in meghalaya": "Bamboo baskets, cane furniture, and handwoven textiles.",
  "best market for souvenirs": "Police Bazaar has a wide range of souvenirs.",
  "organic products in meghalaya": "Organic turmeric and black pepper are famous exports.",
  "are oranges famous in meghalaya": "Yes, Sohra oranges are very popular.",
  "price of organic honey": "Organic honey costs ₹300–₹600 per kg.",
  "cost of bamboo items": "Small bamboo crafts cost ₹100–₹300.",
  "best time for shopping festivals": "During Christmas and New Year, markets are very vibrant.",

  // ===================== TRANSPORT =====================
  "how to reach shillong from guwahati": "By road, about 100 km. Shared taxi costs ~₹500, private ~₹2000.",
  "nearest airport to shillong": "Umroi Airport (Shillong Airport), 30 km from the city.",
  "is there a railway station in shillong": "No, the nearest major railway station is Guwahati.",
  "do ola or uber work in shillong": "No, but local taxis are available.",
  "how much is taxi guwahati to shillong": "Shared taxi ~₹500, private ~₹2000.",
  "bus service guwahati to shillong": "Yes, buses are available from ASTC at ₹150–₹300.",
  "local transport in shillong": "Taxis are the main local transport.",
  "how much taxi in shillong": "Local taxis charge ₹100–₹300 depending on distance.",
  "renting a bike in shillong": "Bike rentals are ₹800–₹1200 per day.",
  "fuel price in meghalaya": "Petrol is around ₹95–₹100 per litre.",

  // ===================== HOTELS & STAYS =====================
  "budget hotels in shillong": "Hotel Centre Point, Alpine Continental, Pinewood Hotel.",
  "average hotel price in shillong": "₹1200–₹4000 per night.",
  "luxury hotels in meghalaya": "Ri Kynjai Resort and Polo Towers.",
  "homestays in cherrapunji": "Homestays start from ₹800 per night.",
  "can i find airbnb in meghalaya": "Yes, Airbnb has listings in Shillong and Cherrapunji.",
  "hotel near police bazaar": "Hotel Pegasus Crown is a good option.",
  "are hotels cheap in meghalaya": "Yes, you can find budget hotels from ₹800 onwards.",
  "room tariff ri kynjai resort": "Rooms start from ₹6000 per night.",
  "do hotels accept card payments": "Yes, most mid-range and luxury hotels accept cards.",
  "is wifi available in hotels": "Yes, most hotels provide free WiFi.",

  // ===================== CULTURE & FESTIVALS =====================
  "famous festivals of meghalaya": "Wangala, Shad Suk Mynsiem, Nongkrem Dance.",
  "when is wangala festival": "Wangala festival is celebrated in November.",
  "what is shad suk mynsiem": "It’s a Khasi spring festival meaning 'Dance of the Joyous Heart'.",
  "tribes of meghalaya": "Khasi, Garo, and Jaintia are the three main tribes.",
  "meghalaya traditional dance": "Wangala Dance and Nongkrem Dance are popular.",
  "meghalaya traditional attire": "Jainsem (for Khasi women) and Jymphong (for men).",
  "religion in meghalaya": "Christianity is the major religion.",
  "traditional music in meghalaya": "Flutes, drums, and tribal folk music are common.",
  "is wangala harvest festival": "Yes, it’s the harvest festival of the Garo tribe.",
  "christmas in shillong": "Shillong is beautifully decorated for Christmas.",

  // ===================== SAFETY & TIPS =====================
  "is meghalaya safe at night": "Yes, Meghalaya is relatively safe at night, but avoid isolated areas.",
  "is alcohol available in meghalaya": "Yes, alcohol is available in bars and shops.",
  "is meghalaya safe for women": "Yes, Meghalaya is considered safe for women travelers.",
  "medical facilities in shillong": "NEIGRIHMS and Woodland Hospital are major facilities.",
  "is meghalaya expensive": "Meghalaya is moderately priced compared to other tourist destinations.",
  "do i need permit to visit meghalaya": "No permit is required for Indian tourists.",
  "is meghalaya safe during rains": "Yes, but landslides may occur in monsoon.",
  "vaccinations required for meghalaya": "No special vaccinations are required.",
  "is meghalaya clean": "Yes, especially Mawlynnong, the cleanest village in Asia.",
  "what is the drinking age": "The legal drinking age in Meghalaya is 18.",

  // ===================== WEATHER =====================
  "weather in meghalaya in december": "Cold, 5–15°C, pleasant for travel.",
  "weather in meghalaya in july": "Heavy rainfall, monsoon season.",
  "average rainfall in meghalaya": "Around 12,000 mm annually, one of the wettest places on Earth.",
  "does it snow in meghalaya": "No, it doesn’t snow in Meghalaya.",
  "summer temperature in meghalaya": "15–25°C in summer months.",
  "monsoon season meghalaya": "June to September is monsoon season.",
  "best season for waterfalls": "Monsoon is best for waterfalls, though travel may be tough.",
  "winter clothes needed in meghalaya": "Yes, carry sweaters and jackets.",
  "humidity in meghalaya": "Humidity is high, around 70–80%.",
  "sunrise time in shillong": "Around 5:00 AM in summer, 6:00 AM in winter."
  
  const meghalayaQA = {
  // ===================== GENERAL INFO =====================
  "what is the capital of meghalaya": "Shillong is the capital of Meghalaya.",
  "where is meghalaya located": "Meghalaya is in Northeast India, bordered by Assam and Bangladesh.",
  "what is the meaning of meghalaya": "Meghalaya means 'Abode of Clouds' in Sanskrit.",
  "is meghalaya safe for solo travelers": "Yes, Meghalaya is one of the safest states in India for solo travelers.",
  "what language is spoken in meghalaya": "Khasi, Garo, Jaintia, and English are widely spoken.",
  "what is the population of meghalaya": "Meghalaya has a population of about 3.5 million.",
  "best time to visit meghalaya": "October to April is the best time to visit Meghalaya.",
  "how many districts are in meghalaya": "There are 12 districts in Meghalaya.",
  "currency used in meghalaya": "Indian Rupee (INR) is used in Meghalaya.",
  "famous nickname of meghalaya": "Meghalaya is called the 'Scotland of the East'.",

  // ===================== ATTRACTIONS =====================
  "famous places in shillong": "Ward’s Lake, Shillong Peak, Elephant Falls, Police Bazaar.",
  "tell me about cherrapunji": "Cherrapunji is famous for its heavy rainfall, living root bridges, and Nohkalikai Falls.",
  "how tall is nohkalikai falls": "Nohkalikai Falls is 340 meters tall, the tallest plunge waterfall in India.",
  "double decker root bridge trek time": "The trek takes around 3–4 hours round trip.",
  "what is dawki famous for": "Dawki is famous for its crystal-clear Umngot River where boats seem to float in the air.",
  "cleanest village in asia": "Mawlynnong in Meghalaya is known as the cleanest village in Asia.",
  "famous caves in meghalaya": "Mawsmai Cave, Siju Cave, and Liat Prah are popular caves.",
  "what is shillong peak": "Shillong Peak offers panoramic views of the city and surroundings.",
  "popular waterfall in meghalaya": "Krang Suri Falls is one of the most scenic waterfalls.",
  "living root bridge location": "They are found in Cherrapunji and Mawlynnong region.",

  // ===================== FOOD & PRICES =====================
  "famous food of meghalaya": "Jadoh, Doh Khleh, Tungrymbai, and Bamboo Shoots.",
  "price of jadoh": "Jadoh costs around ₹80–₹150 per plate.",
  "price of khasi pork curry": "Khasi pork curry is about ₹150–₹250 per plate.",
  "cost of bamboo shoot pickle": "Around ₹50–₹100 per jar in local markets.",
  "where to eat local food in shillong": "Police Bazaar and local Khasi eateries are great options.",
  "what is tungrymbai": "Tungrymbai is a fermented soybean dish cooked with pork.",
  "vegetarian food in meghalaya": "Yes, you can find vegetarian food like Jhur Sideh and Pumaloi.",
  "street food in shillong": "Momos, chowmein, and jadoh are common street foods.",
  "cost of momos in shillong": "Momos cost about ₹50–₹120 per plate.",
  "cost of tea in meghalaya": "A cup of tea costs ₹10–₹20.",

  // ===================== SHOPPING =====================
  "where to shop in shillong": "Police Bazaar and Bara Bazaar are popular shopping hubs.",
  "famous things to buy in meghalaya": "Handwoven shawls, bamboo crafts, organic honey, oranges.",
  "price of khasi shawls": "Khasi shawls cost ₹500–₹1200 depending on material.",
  "local handicrafts in meghalaya": "Bamboo baskets, cane furniture, and handwoven textiles.",
  "best market for souvenirs": "Police Bazaar has a wide range of souvenirs.",
  "organic products in meghalaya": "Organic turmeric and black pepper are famous exports.",
  "are oranges famous in meghalaya": "Yes, Sohra oranges are very popular.",
  "price of organic honey": "Organic honey costs ₹300–₹600 per kg.",
  "cost of bamboo items": "Small bamboo crafts cost ₹100–₹300.",
  "best time for shopping festivals": "During Christmas and New Year, markets are very vibrant.",

  // ===================== TRANSPORT =====================
  "how to reach shillong from guwahati": "By road, about 100 km. Shared taxi costs ~₹500, private ~₹2000.",
  "nearest airport to shillong": "Umroi Airport (Shillong Airport), 30 km from the city.",
  "is there a railway station in shillong": "No, the nearest major railway station is Guwahati.",
  "do ola or uber work in shillong": "No, but local taxis are available.",
  "how much is taxi guwahati to shillong": "Shared taxi ~₹500, private ~₹2000.",
  "bus service guwahati to shillong": "Yes, buses are available from ASTC at ₹150–₹300.",
  "local transport in shillong": "Taxis are the main local transport.",
  "how much taxi in shillong": "Local taxis charge ₹100–₹300 depending on distance.",
  "renting a bike in shillong": "Bike rentals are ₹800–₹1200 per day.",
  "fuel price in meghalaya": "Petrol is around ₹95–₹100 per litre.",

  // ===================== HOTELS & STAYS =====================
  "budget hotels in shillong": "Hotel Centre Point, Alpine Continental, Pinewood Hotel.",
  "average hotel price in shillong": "₹1200–₹4000 per night.",
  "luxury hotels in meghalaya": "Ri Kynjai Resort and Polo Towers.",
  "homestays in cherrapunji": "Homestays start from ₹800 per night.",
  "can i find airbnb in meghalaya": "Yes, Airbnb has listings in Shillong and Cherrapunji.",
  "hotel near police bazaar": "Hotel Pegasus Crown is a good option.",
  "are hotels cheap in meghalaya": "Yes, you can find budget hotels from ₹800 onwards.",
  "room tariff ri kynjai resort": "Rooms start from ₹6000 per night.",
  "do hotels accept card payments": "Yes, most mid-range and luxury hotels accept cards.",
  "is wifi available in hotels": "Yes, most hotels provide free WiFi.",

  // ===================== CULTURE & FESTIVALS =====================
  "famous festivals of meghalaya": "Wangala, Shad Suk Mynsiem, Nongkrem Dance.",
  "when is wangala festival": "Wangala festival is celebrated in November.",
  "what is shad suk mynsiem": "It’s a Khasi spring festival meaning 'Dance of the Joyous Heart'.",
  "tribes of meghalaya": "Khasi, Garo, and Jaintia are the three main tribes.",
  "meghalaya traditional dance": "Wangala Dance and Nongkrem Dance are popular.",
  "meghalaya traditional attire": "Jainsem (for Khasi women) and Jymphong (for men).",
  "religion in meghalaya": "Christianity is the major religion.",
  "traditional music in meghalaya": "Flutes, drums, and tribal folk music are common.",
  "is wangala harvest festival": "Yes, it’s the harvest festival of the Garo tribe.",
  "christmas in shillong": "Shillong is beautifully decorated for Christmas.",

  // ===================== SAFETY & TIPS =====================
  "is meghalaya safe at night": "Yes, Meghalaya is relatively safe at night, but avoid isolated areas.",
  "is alcohol available in meghalaya": "Yes, alcohol is available in bars and shops.",
  "is meghalaya safe for women": "Yes, Meghalaya is considered safe for women travelers.",
  "medical facilities in shillong": "NEIGRIHMS and Woodland Hospital are major facilities.",
  "is meghalaya expensive": "Meghalaya is moderately priced compared to other tourist destinations.",
  "do i need permit to visit meghalaya": "No permit is required for Indian tourists.",
  "is meghalaya safe during rains": "Yes, but landslides may occur in monsoon.",
  "vaccinations required for meghalaya": "No special vaccinations are required.",
  "is meghalaya clean": "Yes, especially Mawlynnong, the cleanest village in Asia.",
  "what is the drinking age": "The legal drinking age in Meghalaya is 18.",

  // ===================== WEATHER =====================
  "weather in meghalaya in december": "Cold, 5–15°C, pleasant for travel.",
  "weather in meghalaya in july": "Heavy rainfall, monsoon season.",
  "average rainfall in meghalaya": "Around 12,000 mm annually, one of the wettest places on Earth.",
  "does it snow in meghalaya": "No, it doesn’t snow in Meghalaya.",
  "summer temperature in meghalaya": "15–25°C in summer months.",
  "monsoon season meghalaya": "June to September is monsoon season.",
  "best season for waterfalls": "Monsoon is best for waterfalls, though travel may be tough.",
  "winter clothes needed in meghalaya": "Yes, carry sweaters and jackets.",
  "humidity in meghalaya": "Humidity is high, around 70–80%.",
  "sunrise time in shillong": "Around 5:00 AM in summer, 6:00 AM in winter."
};
  Object.assign(meghalayaQA, {
  // ===================== TREKKING & ADVENTURE =====================
  "best treks in meghalaya": "Double Decker Living Root Bridge Trek, David Scott Trail, Mawphlang Sacred Grove trek.",
  "trekking difficulty double decker bridge": "Moderate, with many stairs, takes 3–4 hours.",
  "cost of trekking guide": "Around ₹800–₹1500 per trek depending on distance.",
  "is camping allowed in meghalaya": "Yes, camping is allowed in Dawki and Mawlyngbna with permission.",
  "what to pack for trekking in meghalaya": "Comfortable shoes, raincoat, water bottle, energy bars.",
  "adventure sports in dawki": "Kayaking, boating, cliff jumping.",
  "zipline in meghalaya": "Yes, Mawkdok has zipline activities starting at ₹500.",
  "river activities in dawki": "Boating costs ₹500–₹1000 depending on distance.",
  "best cave exploration": "Mawsmai Cave and Arwah Cave are tourist-friendly caves.",
  "caving cost in meghalaya": "Guided cave tours cost ₹300–₹800.",

  // ===================== FLIGHTS =====================
  "nearest airport to cherrapunji": "Umroi Airport, 80 km away, but Guwahati Airport is more convenient.",
  "cheap flights to shillong": "Indigo and Alliance Air operate flights to Umroi.",
  "flight guwahati to shillong": "Alliance Air operates small ATR flights, ~₹2500–₹4000.",
  "does shillong airport have flights": "Yes, but limited connectivity.",
  "international airport near meghalaya": "Lokpriya Gopinath Bordoloi International Airport, Guwahati.",
  "is there a direct flight to shillong from delhi": "Yes, some airlines operate direct flights from Delhi.",
  "how long is flight delhi to guwahati": "Around 2.5 hours.",
  "airlines flying to shillong": "Indigo, SpiceJet, and Alliance Air.",
  "can i book flights online": "Yes, flights can be booked online on major travel portals.",
  "baggage limit shillong flights": "Usually 15kg check-in and 7kg cabin for domestic flights.",

  // ===================== FLORA & FAUNA =====================
  "wildlife sanctuaries in meghalaya": "Balpakram National Park, Nokrek National Park, Siju Sanctuary.",
  "animals found in meghalaya": "Clouded leopard, wild buffalo, Asian elephants, hoolock gibbons.",
  "famous birding spots": "Nokrek National Park and Shillong Peak.",
  "flora of meghalaya": "Orchids, pine forests, and tropical plants.",
  "rare plants in meghalaya": "Pitcher plants are found here.",
  "is meghalaya rich in biodiversity": "Yes, it’s one of the biodiversity hotspots in India.",
  "balpakram national park location": "Located in South Garo Hills.",
  "nokrek biosphere reserve": "UNESCO biosphere reserve, home to red panda-like primates.",
  "fishing in meghalaya": "Yes, in Dawki and Rymben rivers.",
  "butterflies in meghalaya": "Meghalaya is home to more than 100 species of butterflies.",

  // ===================== ECONOMY & PEOPLE =====================
  "main occupation in meghalaya": "Agriculture is the main occupation.",
  "crops grown in meghalaya": "Rice, maize, potatoes, pineapples, oranges.",
  "is coal mining in meghalaya": "Yes, rat-hole coal mining exists but is restricted.",
  "famous industry in meghalaya": "Handloom and handicrafts.",
  "income source of locals": "Agriculture, tourism, and small businesses.",
  "population density meghalaya": "Around 130 per sq km.",
  "is meghalaya urban or rural": "Mostly rural with some urban centers like Shillong.",
  "meghalaya literacy rate": "Around 75%.",
  "life expectancy in meghalaya": "Around 70 years.",
  "who are khasis": "Khasi are one of the main tribes in Meghalaya.",

  // ===================== PRICES & DAILY EXPENSES =====================
  "daily budget for meghalaya trip": "Budget travelers: ₹1500/day, Mid-range: ₹3000/day.",
  "cost of local taxi shillong": "₹100–₹300 for short distances.",
  "cost of bus travel shillong": "₹10–₹30 per ride.",
  "average meal price in meghalaya": "₹100–₹250 per person.",
  "beer price in shillong": "₹150–₹200 per bottle in restaurants.",
  "vegetables cost in meghalaya": "Around ₹30–₹60 per kg in markets.",
  "fruit prices meghalaya": "Oranges ~₹50/kg, Pineapples ~₹30/kg.",
  "handicraft souvenir cost": "Small souvenirs ₹100–₹500.",
  "hotel budget range": "Budget: ₹1000–₹1500, Luxury: ₹5000+.",
  "is meghalaya expensive for tourists": "No, it’s affordable compared to other tourist states.",

  // ===================== HISTORY =====================
  "when was meghalaya formed": "Meghalaya was formed on 21 January 1972.",
  "who was first cm of meghalaya": "Captain Williamson Sangma was the first CM.",
  "freedom movement in meghalaya": "Shillong was an important hub during freedom struggle.",
  "colonial history shillong": "Shillong was the capital of composite Assam under the British.",
  "tribal kingdoms meghalaya": "Khasi, Garo, and Jaintia kings ruled before British annexation.",
  "state animal of meghalaya": "Clouded Leopard.",
  "state bird of meghalaya": "Hill Myna.",
  "state flower of meghalaya": "Lady’s Slipper Orchid.",
  "state tree of meghalaya": "Indian White Teak.",
  "is shillong british heritage town": "Yes, it was a hill station under the British.",

  // ===================== LOCAL LIFE =====================
  "market days in meghalaya": "Iewduh (Bara Bazaar) is the largest traditional market in Shillong.",
  "is sunday holiday in meghalaya": "Yes, most shops remain closed on Sundays.",
  "local transport timing": "Taxis operate from 6 AM to 8 PM.",
  "school education language": "English is the medium in most schools.",
  "healthcare in meghalaya": "Public hospitals and private clinics exist.",
  "are locals friendly": "Yes, Meghalayan people are very warm and hospitable.",
  "matrilineal system meghalaya": "Yes, Khasi and Garo follow matrilineal system where lineage passes through mother.",
  "inheritance rules meghalaya": "Youngest daughter usually inherits property in Khasi culture.",
  "local festivals in shillong": "Shillong Autumn Festival is very popular.",
  "music scene in shillong": "Shillong is called the 'Rock Capital of India'.",

  // ===================== ROADS & DISTANCES =====================
  "distance guwahati to shillong": "Around 100 km, 3 hours by road.",
  "distance shillong to cherrapunji": "Around 55 km, 2 hours by road.",
  "distance shillong to dawki": "Around 82 km, 3 hours by road.",
  "distance shillong to mawlynnong": "Around 90 km, 3 hours by road.",
  "distance cherrapunji to dawki": "Around 85 km, 3 hours by road.",
  "road condition meghalaya": "Good highways but narrow in some places.",
  "bike trip guwahati to shillong": "Yes, possible and scenic.",
  "petrol pumps on the way": "Yes, available at regular intervals.",
  "road trip cost guwahati to meghalaya": "Around ₹1500–₹2000 by car.",
  "toll charges guwahati to shillong": "₹50–₹100 depending on vehicle.",

  // ===================== EDUCATION =====================
  "universities in meghalaya": "NEHU (North-Eastern Hill University), IIM Shillong, NIFT Shillong.",
  "is there iim in meghalaya": "Yes, IIM Shillong is located here.",
  "best colleges in shillong": "St. Edmund’s College, St. Anthony’s College, NEHU.",
  "schooling system in meghalaya": "Schools are mostly private or missionary-run.",
  "literacy rate in shillong": "Around 85%.",
  "medium of education": "Mostly English and Khasi.",
  "are there technical colleges": "Yes, NIT Meghalaya is in Shillong.",
  "is shillong good for education": "Yes, it’s an education hub of Northeast India.",
  "famous alumni from meghalaya": "Conrad Sangma (CM), Patricia Mukhim (journalist).",
  "do students come from other states": "Yes, many students come to Shillong for higher education."
});
// … Continue until 500 entries Object.assign(meghalayaQA, {
  // ===================== FESTIVALS & EVENTS =====================
  "does meghalaya celebrate christmas": "Yes, Christmas is celebrated grandly, especially in Shillong.",
  "what is nongkrem dance festival": "It’s a Khasi thanksgiving festival held in November at Smit village.",
  "shad suk mynsiem meaning": "It means 'Dance of the Joyous Heart', celebrated in spring.",
  "wangala festival significance": "Harvest festival of the Garo tribe, with drums and dances.",
  "are there music festivals in meghalaya": "Yes, Shillong hosts Autumn Festival and NH7 Weekender.",
  "shillong autumn festival": "Held in November, celebrating music, culture, and food.",
  "does meghalaya celebrate holi": "Not widely, mostly in urban areas.",
  "does meghalaya celebrate diwali": "Not much, since majority are Christians.",
  "new year celebrations shillong": "Huge celebrations with live music and fireworks.",
  "are local weddings big": "Yes, Khasi and Garo weddings are rich in traditions.",

  // ===================== TRANSPORT CONTINUED =====================
  "how to reach meghalaya from kolkata": "By flight to Guwahati and then road to Shillong.",
  "is there train to meghalaya": "No direct train, nearest is Guwahati Railway Station.",
  "cab fare shillong sightseeing": "₹1500–₹3000 for a full day depending on spots.",
  "bike rental cost per day": "₹800–₹1200 including helmet.",
  "is fuel expensive in meghalaya": "Similar to rest of India, ~₹95–₹100 per litre.",
  "airport to shillong taxi fare": "₹1500–₹2000 from Guwahati Airport.",
  "shared sumo service": "Yes, shared Sumo costs around ₹500 per person Guwahati–Shillong.",
  "local bus service in shillong": "Limited but available, ₹10–₹30 per ride.",
  "night travel in meghalaya": "Not common, best to travel during daytime.",
  "self drive car rental meghalaya": "₹2500–₹4000 per day depending on vehicle.",

  // ===================== CULTURE & TRADITIONS =====================
  "is meghalaya matrilineal": "Yes, Khasi and Garo tribes follow matrilineal tradition.",
  "inheritance rule khasi tribe": "The youngest daughter inherits the ancestral property.",
  "role of men in khasi society": "Men participate in governance, though property passes through women.",
  "meghalaya traditional music": "Folk songs with flutes, drums, and traditional dances.",
  "clothing of khasi women": "Jainsem, a two-piece garment with a shawl.",
  "clothing of garo tribe": "Dakmanda for women and turban-style headgear for men.",
  "traditional ornaments in meghalaya": "Coral, silver, and gold jewelry are worn in ceremonies.",
  "meghalaya marriage customs": "Marriage usually happens outside one’s clan.",
  "role of elders in society": "Elders have high respect in decision making.",
  "is divorce allowed": "Yes, in matrilineal tribes, divorce is accepted socially.",

  // ===================== WEATHER DETAILS =====================
  "temperature in shillong in winter": "Around 4–15°C, chilly but pleasant.",
  "rainiest place in meghalaya": "Mawsynram, the wettest place on Earth.",
  "best time for sightseeing": "October to April, post monsoon season.",
  "summer temperature shillong": "15–25°C, quite mild.",
  "winter packing list": "Woolens, jackets, gloves, and warm socks.",
  "monsoon challenges": "Landslides, roadblocks, and heavy fog.",
  "cloud cover meghalaya": "Frequent, hence the name 'Abode of Clouds'.",
  "can fog be dangerous": "Yes, driving in fog requires caution.",
  "humidity levels meghalaya": "High, around 70–90%.",
  "does meghalaya get cyclones": "Rare, but heavy rainfall is common.",

  // ===================== TOURISM PACKAGES =====================
  "average meghalaya tour package": "₹15,000–₹25,000 for 5–7 days.",
  "honeymoon package shillong": "₹20,000–₹35,000 including hotels and sightseeing.",
  "budget travel cost": "₹1500 per day including food and stay.",
  "luxury travel meghalaya": "₹50,000+ for premium resorts and tours.",
  "student trip cost": "₹5000–₹10,000 for a short trip.",
  "is camping cheap": "Yes, ₹500–₹1500 per night for camping.",
  "trekking package cost": "₹5000–₹8000 depending on trek.",
  "cherrapunji day trip cost": "₹2000–₹4000 by cab.",
  "dawki boating package": "₹500–₹1000 per person.",
  "package tours available": "Yes, many agencies in Police Bazaar offer packages.",

  // ===================== LOCAL ITEMS & SHOPPING =====================
  "is bamboo craft famous": "Yes, bamboo and cane crafts are famous.",
  "cost of cane furniture": "Small chairs ~₹1500, larger ones ₹3000+.",
  "cost of shawls meghalaya": "₹500–₹1500 depending on weaving.",
  "jewelry price in meghalaya": "Handmade ornaments start at ₹200.",
  "best souvenir to buy": "Khasi shawls and bamboo items.",
  "cost of orange per kg": "₹50–₹70 depending on season.",
  "pineapple price meghalaya": "₹30–₹50 per piece.",
  "is black pepper grown": "Yes, organic black pepper is famous here.",
  "turmeric price": "₹150–₹250 per kg.",
  "handmade basket price": "₹100–₹300 in local markets.",

  // ===================== HEALTH & SAFETY =====================
  "nearest hospital shillong": "NEIGRIHMS is the largest hospital in Shillong.",
  "pharmacies in meghalaya": "Easily available in cities like Shillong.",
  "emergency number meghalaya": "Dial 100 for police, 108 for ambulance.",
  "covid rules in meghalaya": "Masks not mandatory now, but health protocols followed.",
  "is safe for elderly": "Yes, but avoid steep treks.",
  "drinking water safe": "Bottled water recommended for tourists.",
  "insurance for trips": "Yes, travel insurance is recommended.",
  "crime rate in meghalaya": "Low compared to many Indian states.",
  "women safety in meghalaya": "Meghalaya is considered safe for women.",
  "nightlife in shillong": "Shillong has pubs, cafes, and live music scenes.",

  // ===================== UNIQUE EXPERIENCES =====================
  "living root bridge age": "Some bridges are more than 500 years old.",
  "umngot river specialty": "Crystal clear water, boats look like they’re floating.",
  "cleanest village in asia": "Mawlynnong, located near Dawki.",
  "sacred forest meghalaya": "Mawphlang Sacred Grove, protected by Khasi rituals.",
  "skywalk in meghalaya": "Mawlynnong has a bamboo skywalk with great views.",
  "is shillong called scotland of east": "Yes, due to its rolling hills and beauty.",
  "heritage sites in shillong": "Don Bosco Museum, All Saints Cathedral.",
  "root bridge trekking tips": "Carry water, wear good shoes, be prepared for stairs.",
  "camping by rivers": "Yes, Dawki offers riverside camping.",
  "famous music bands shillong": "Soulmate and many rock bands originated here.",

  // ===================== LANGUAGE VARIATIONS =====================
  "khublei means": "Khublei means 'Thank you' in Khasi.",
  "how to say hello in khasi": "You can say 'Khublei Shibun'.",
  "how to say hello in garo": "Say 'Chibai'.",
  "how to say good morning in khasi": "Khublei ka sngi.",
  "common greeting in shillong": "People often say 'Khublei'.",
  "do people understand hindi": "Yes, many people understand Hindi.",
  "english spoken in meghalaya": "Yes, English is widely spoken.",
  "language in cherrapunji": "Khasi is common, but Hindi/English works too.",
  "language in dawki": "Khasi and Bengali are spoken, English works.",
  "language barrier issue": "No, tourists can manage with English or Hindi."
};
Object.assign(meghalayaQA, {
  // ===================== ADVENTURE ACTIVITIES =====================
  "paragliding in meghalaya": "Yes, paragliding is available in Shillong and Jowai, ~₹2500 per flight.",
  "kayaking in dawki": "Kayaking is available for ₹500–₹800 per session.",
  "camping at dawki cost": "₹800–₹1500 per night with tents and food.",
  "zipline in meghalaya": "Yes, Dawki and Sohra have ziplining, ~₹400–₹800.",
  "trekking trails in meghalaya": "Popular treks include Double Decker Root Bridge and David Scott Trail.",
  "caving in meghalaya": "Meghalaya has famous caves like Mawsmai, Siju, and Arwah.",
  "river rafting in meghalaya": "Rafting is available in Dawki Umngot River, ₹1000–₹1500 per person.",
  "cycling in meghalaya": "Adventure cycling tours are available in Shillong and Sohra.",
  "angling in meghalaya": "Angling is popular in Umiam Lake and Dawki River.",
  "rock climbing in meghalaya": "Yes, adventure clubs offer rock climbing in Sohra.",

  // ===================== FOOD & CUISINE =====================
  "traditional food of khasi": "Jadoh (rice with meat), Dohneiiong (pork curry), Tungrymbai (fermented soybean).",
  "famous garo dishes": "Nokham (dry fish with chilies), Wak Pura (pork with rice powder).",
  "pork dishes in meghalaya": "Pork is very popular, especially Dohneiiong.",
  "vegetarian options": "Yes, tungrymbai, putharo, pickles, and rice dishes.",
  "street food in shillong": "Momos, chowmein, fried rice, and tea stalls are common.",
  "local alcohol in meghalaya": "Rice beer, called 'Kyat', is traditional.",
  "is beef available": "Yes, beef is widely eaten in Meghalaya.",
  "fish dishes in meghalaya": "Fish chutneys and curries are common, especially in Garo Hills.",
  "desserts in meghalaya": "Pukhlein (rice flour and jaggery), sweet rice cakes.",
  "cost of meal in shillong": "₹150–₹300 for local meals.",

  // ===================== HIDDEN GEMS =====================
  "unknown places in meghalaya": "Krang Suri Falls, Mawphanlur, Laitlum Canyons.",
  "krang suri falls speciality": "A turquoise blue waterfall with swimming options.",
  "laitlum canyon view": "Panoramic valley views, often used in films.",
  "mawphanlur village": "A serene village with lakes, great for camping.",
  "nongkhnum island": "Second largest river island in Asia, located in West Khasi Hills.",
  "pynursla meghalaya": "Famous for root bridges and scenic drives.",
  "umden silk village": "Known for eri silk production.",
  "nongriat double decker root bridge": "Iconic double-decker living root bridge trek.",
  "arwah cave specialty": "Fossils and limestone formations.",
  "siju cave garo hills": "One of India’s longest caves.",

  // ===================== FLIGHT DETAILS =====================
  "nearest airport to meghalaya": "Shillong Airport (Umroi) is the nearest, but Guwahati Airport is bigger.",
  "shillong airport code": "SHL is the airport code.",
  "guwahati to shillong distance": "Around 120 km, 3–4 hours by road.",
  "flights to shillong": "Flights connect Shillong to Kolkata and Delhi.",
  "domestic airlines to shillong": "Alliance Air and Indigo operate here.",
  "baggage allowance": "Varies, usually 15kg check-in + 7kg cabin.",
  "taxi fare from airport": "₹2000 approx. from Guwahati to Shillong.",
  "is international flight available": "No, nearest international airport is Guwahati.",
  "shillong airport facilities": "Basic, with small lounge and cafe.",
  "cheap flights to meghalaya": "Book early from Kolkata or Delhi for lower fares.",

  // ===================== HISTORY & HERITAGE =====================
  "who are the khasis": "Indigenous people of Meghalaya with matrilineal traditions.",
  "who are the garos": "One of the three major tribes, mostly in Garo Hills.",
  "who are the jaintias": "Tribe from Jaintia Hills, known for unique festivals.",
  "colonial history of shillong": "Shillong was the capital of Assam during British rule.",
  "statehood year of meghalaya": "Meghalaya became a state in 1972.",
  "is shillong british era town": "Yes, it has many colonial buildings.",
  "heritage churches in shillong": "All Saints Cathedral and Cathedral of Mary Help of Christians.",
  "don bosco museum importance": "Showcases culture of Northeast India.",
  "ancient monuments meghalaya": "Monoliths and sacred stones in Khasi Hills.",
  "freedom movement in meghalaya": "Tribal leaders resisted British rule.",

  // ===================== ECO TOURISM =====================
  "is eco tourism popular": "Yes, with focus on community-based tourism.",
  "cleanest village asia": "Mawlynnong is Asia’s cleanest village.",
  "sustainable tourism meghalaya": "Local communities manage homestays and eco parks.",
  "plastic ban in meghalaya": "Plastic is discouraged in many areas.",
  "is mawphlang sacred forest protected": "Yes, it’s a biodiversity hotspot with spiritual importance.",
  "organic farming in meghalaya": "Widely practiced with organic crops.",
  "community homestays meghalaya": "Yes, many homestays run by local families.",
  "bamboo bridges meghalaya": "Handmade bamboo bridges are common in villages.",
  "wildlife sanctuaries meghalaya": "Balpakram, Nokrek, Siju, and Nongkhyllem.",
  "rare orchids meghalaya": "More than 300 species of orchids grow here.",

  // ===================== SHOPPING CONTINUED =====================
  "police bazaar shopping": "Main market in Shillong for clothes, souvenirs, and food.",
  "bara bazaar shillong": "Traditional market where locals buy goods.",
  "laher bazaar": "Known for Khasi traditional attire and jewelry.",
  "handicraft shops in shillong": "Government emporiums and local stalls.",
  "price of bamboo hat": "₹200–₹400 depending on size.",
  "cost of khasi shawl": "₹700–₹2000 depending on material.",
  "best place to buy tea": "Police Bazaar and Shillong tea stores.",
  "organic honey price": "₹300–₹500 per bottle.",
  "black rice price meghalaya": "₹150–₹200 per kg.",
  "souvenir shops in cherrapunji": "Yes, many near waterfalls and tourist points.",

  // ===================== RELIGION & SPIRITUALITY =====================
  "dominant religion in meghalaya": "Christianity is the majority religion.",
  "churches in shillong": "Cathedral of Mary Help of Christians is famous.",
  "animism in meghalaya": "Still followed in some tribes alongside Christianity.",
  "hindu temples in meghalaya": "Few temples in Shillong and Jowai.",
  "mosques in meghalaya": "Small Muslim communities exist, especially in towns.",
  "sacred groves meaning": "Forests protected by tribal religious beliefs.",
  "buddhism in meghalaya": "Minor presence, not common.",
  "is sunday a holiday": "Yes, most shops are closed on Sundays.",
  "spiritual tourism meghalaya": "Sacred forests and old churches attract tourists.",
  "role of rituals in tourism": "Many festivals and dances are tied to rituals.",

  // ===================== FESTIVAL FOLLOW-UPS =====================
  "do tourists join nongkrem dance": "Yes, tourists can watch and sometimes participate.",
  "wangala festival month": "Usually in November.",
  "shad suk mynsiem held where": "At Weiking Grounds, Shillong.",
  "is khasi new year celebrated": "Yes, through Shad Suk Mynsiem festival.",
  "harvest festival in jaintia hills": "Behdienkhlam festival in July.",
  "is behdienkhlam unique": "Yes, men carry large wooden structures in a procession.",
  "tourists join behdienkhlam": "Yes, tourists are welcome to watch.",
  "does shillong celebrate holi": "Limited celebrations, mainly in non-tribal areas.",
  "christmas decorations in shillong": "Shillong is beautifully decorated with lights.",
  "new year events tickets": "₹500–₹2000 depending on the event."
});
Object.assign(meghalayaQA, {
  // ===================== WEATHER & SEASONS =====================
  "is meghalaya cold": "Yes, Shillong and Cherrapunji are cool year-round.",
  "summer temperature meghalaya": "15°C–25°C in most parts.",
  "winter temperature meghalaya": "4°C–12°C in higher altitudes.",
  "rainfall in meghalaya": "One of the wettest places on Earth, 10,000+ mm annually.",
  "best time to visit meghalaya": "October to April for clear skies, June–September for monsoons.",
  "does it snow in meghalaya": "No, Meghalaya doesn’t usually get snow.",
  "what clothes to carry": "Light woolens, raincoat, trekking shoes.",
  "monsoon travel tips": "Carry umbrellas, rain jackets, and waterproof shoes.",
  "foggy season in meghalaya": "Winters and monsoons often have dense fog.",
  "when is driest season": "December to February is comparatively dry.",

  // ===================== LOCAL TRANSPORT =====================
  "local taxi fare shillong": "₹200–₹400 within the city.",
  "shared sumo fares": "Shillong to Cherrapunji ~₹200, Shillong to Dawki ~₹300.",
  "night buses meghalaya": "Limited night services, most travel is daytime.",
  "bike rental shillong": "₹1000–₹1500 per day with documents.",
  "car rental meghalaya": "₹2500–₹4000 per day with driver.",
  "app cabs in shillong": "Yes, apps like Ola are limited, but local taxis are common.",
  "shillong local bus": "City buses and shared taxis are available.",
  "airport taxi rate": "₹2000 from Guwahati to Shillong.",
  "petrol price meghalaya": "Around ₹95–₹100 per liter (approx).",
  "is hitchhiking safe": "Not common, better to use shared taxis.",

  // ===================== HEALTH & SAFETY =====================
  "is meghalaya safe for women": "Yes, Meghalaya is considered one of the safest states for women.",
  "is meghalaya safe for tourists": "Yes, locals are friendly and helpful.",
  "hospital in shillong": "Civil Hospital and NEIGRIHMS are major hospitals.",
  "do i need vaccines": "No special vaccines required, but general travel vaccines recommended.",
  "is tap water safe": "Better to drink bottled or filtered water.",
  "mosquito problem meghalaya": "Mild in some areas, carry repellent.",
  "emergency number meghalaya": "Dial 100 for police, 108 for ambulance.",
  "pharmacy availability": "Easily available in towns and cities.",
  "atm availability": "ATMs are widely available in cities, less in villages.",
  "travel insurance recommended": "Yes, always better to have travel insurance.",

  // ===================== HOTELS & STAY =====================
  "cheap hotels in shillong": "Budget hotels start at ₹1000 per night.",
  "luxury hotels in shillong": "₹5000+ per night, with premium services.",
  "homestays in cherrapunji": "Yes, many homestays run by locals.",
  "airbnb in meghalaya": "Available in Shillong and Sohra.",
  "dormitory stays": "Hostels and dorms available at ₹500–₹800.",
  "room booking offline": "Yes, you can book directly at hotels.",
  "is wifi available": "Yes, in most hotels and cafes.",
  "power cuts in meghalaya": "Occasional, but hotels usually have backup.",
  "hotel booking peak season": "Book 2–3 months in advance for December.",
  "eco lodges meghalaya": "Available near Mawlynnong, Dawki, and Sohra.",

  // ===================== CULTURE & PEOPLE =====================
  "is meghalaya matrilineal": "Yes, property is inherited through the mother.",
  "language spoken in meghalaya": "Khasi, Garo, Jaintia, and English are widely spoken.",
  "is hindi understood": "Yes, Hindi is understood in tourist areas.",
  "english in meghalaya": "Widely spoken, especially in Shillong.",
  "dress culture meghalaya": "Women wear Jainsem, men wear traditional tunics.",
  "sports in meghalaya": "Football is the most popular sport.",
  "music culture shillong": "Known as 'Rock Capital of India'.",
  "famous band from shillong": "Soulmate and many rock bands are based here.",
  "youth culture in meghalaya": "Western influence mixed with tribal traditions.",
  "education in meghalaya": "Shillong has reputed schools and universities.",

  // ===================== SHOPPING & MARKETS =====================
  "best place for souvenirs": "Police Bazaar in Shillong.",
  "traditional jewelry meghalaya": "Handmade beads and silver jewelry.",
  "eri silk cost": "₹1500–₹4000 for sarees and stoles.",
  "bamboo crafts price": "₹200–₹1000 depending on size.",
  "where to buy local spices": "Shillong markets and Jaintia Hills.",
  "handmade shawls meghalaya": "Khasi and Jaintia shawls are popular.",
  "organic tea meghalaya": "Sold in Police Bazaar and tea estates.",
  "black rice cost": "₹150–₹200 per kg.",
  "honey in meghalaya": "₹300–₹500 per bottle.",
  "souvenirs in cherrapunji": "Small stalls near waterfalls.",

  // ===================== LANGUAGE HELP =====================
  "khasi word for hello": "Khublei!",
  "khasi word for thank you": "Khublei shibun.",
  "garo word for hello": "Namaskar.",
  "common phrases for tourists": "Khublei (hello), Kumno phi long? (How are you?).",
  "translation help": "Locals can speak English, Hindi, Khasi, and Garo.",
  "is interpreter needed": "Not necessary, English works fine.",
  "learn khasi quickly": "Start with greetings and numbers.",
  "garo basic words": "Namaskar (hello), Sukbri (thank you).",
  "use of bengali in meghalaya": "Spoken by a minority population.",
  "language barrier in meghalaya": "Minimal for Indian tourists, English helps foreign tourists.",

  // ===================== RANDOM TRAVEL INFO =====================
  "sim card availability meghalaya": "Yes, Airtel, Jio, and BSNL are common.",
  "mobile network in meghalaya": "Good in towns, weak in remote villages.",
  "internet speed shillong": "4G is available, average 20 Mbps.",
  "international tourists meghalaya": "Need Protected Area Permit only for some border areas.",
  "currency used meghalaya": "Indian Rupee (INR).",
  "credit card acceptance": "Accepted in hotels, not in small shops.",
  "upi payments meghalaya": "Very common for taxis, cafes, shops.",
  "laundry service shillong": "Available at most hotels.",
  "bike repair shops": "Available in Shillong and Jowai.",
  "travel agencies in shillong": "Many agencies offer package tours.",

  // ===================== POPULAR ITINERARIES =====================
  "2 day meghalaya itinerary": "Day 1: Shillong sightseeing, Day 2: Cherrapunji waterfalls.",
  "3 day meghalaya itinerary": "Day 1: Shillong, Day 2: Cherrapunji, Day 3: Dawki & Mawlynnong.",
  "5 day meghalaya itinerary": "Shillong → Sohra → Dawki → Mawlynnong → Jowai.",
  "7 day meghalaya itinerary": "Covering Shillong, Sohra, Dawki, Mawlynnong, Jowai, Garo Hills.",
  "honeymoon in meghalaya": "Popular spots: Umiam Lake resorts, Sohra eco lodges.",
  "family trip meghalaya": "Kid-friendly attractions like Ward’s Lake, Elephant Falls.",
  "solo travel in meghalaya": "Safe for solo travelers, especially women.",
  "student budget trip": "Stay in hostels, shared taxis, eat at local dhabas.",
  "luxury travel meghalaya": "High-end resorts in Shillong and Sohra.",
  "backpacking meghalaya": "Hostels, trekking, hitchhiking, and local food.",

  // ===================== FESTIVAL ADD-ONS =====================
  "shillong autumn festival": "Held in October, celebrates culture and music.",
  "cherry blossom festival shillong": "November, when cherry trees bloom pink.",
  "food festivals in meghalaya": "Rice festivals, harvest festivals, and local food fests.",
  "christmas in meghalaya": "Widespread celebrations with lights and music.",
  "new year parties in shillong": "Clubs and cafes host events.",
  "music festivals in shillong": "NH7 Weekender and local rock events.",
  "tribal dances of meghalaya": "Shad Suk Mynsiem, Wangala, Behdienkhlam.",
  "is dance important": "Yes, dance is part of rituals and festivals.",
  "are festivals tourist friendly": "Yes, tourists are warmly welcomed.",
  "best festival for tourists": "Wangala (Garo Hills) and Nongkrem Dance (Khasi Hills).",

  // ===================== FALLBACK =====================
  "default_fallback": "Sorry, I don’t know that yet. Try asking about attractions, food, hotels, or transport in Meghalaya."
});

};
